name: 'Terraform-Deploy'
on:
  - push
jobs:
  terraform:
    name: "Terraform-Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: true
      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Format"
        run: terraform fmt
      - name: "Terraform Validate"
        run: terraform validate

      - name: "Terraform Plan"
        run: terraform plan

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve